name: Release Raw Module

on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   run: rm -rf .github
            -   run: mksquashfs raw/ x2t.raw
            -   name: '更新 Update release'
                uses: zhanghengxin/git-release-private@ice
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    allow_override: true
                    gzip: false
                    prerelease: true
                    tag: ${{ steps.get_version.outputs.VERSION }}
                    files: ./x2t.raw